# Generated by Django 5.0.4 on 2024-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenaje_libros_api', '0004_book_isbn_alter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=256)),
                ('client_direction', models.CharField(default='', max_length=256)),
                ('nif', models.CharField(default='', max_length=256)),
                ('date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(default='', max_length=256)),
                ('base_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_number', models.CharField(default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=256)),
                ('client_direction', models.CharField(default='', max_length=256)),
                ('nif', models.CharField(default='', max_length=256)),
                ('date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(default='', max_length=256)),
                ('base_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_number', models.CharField(default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['pk'],
            },
        ),
    ]
