# Generated by Django 5.0.4 on 2024-09-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenaje_libros_api', '0006_bankaccount_remove_invoice_base_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacenaje_libros_api.bankaccount'),
        ),
    ]
